// Generated by CoffeeScript 1.10.0
(function() {
  var ActionTypes, InputActions, chai, expect, sinon, sinonChai, spy;

  InputActions = require('../../js/actions/InputActions');

  ActionTypes = require('../../js/constants/ActionTypes');

  chai = require('chai');

  sinon = require('sinon');

  sinonChai = require('sinon-chai');

  chai.use(sinonChai);

  spy = sinon.spy;

  expect = chai.expect;

  describe('InputActions', function() {
    beforeEach(function() {
      return this.dispatch = spy();
    });
    return describe('changeText', function() {
      beforeEach(function() {
        var getState, thunk;
        thunk = InputActions.changeText('some new text');
        getState = function() {
          return {
            currentNote: 42
          };
        };
        return thunk(this.dispatch, getState);
      });
      return it('should change the text', function() {
        return expect(this.dispatch).to.have.been.calledWith({
          type: ActionTypes.TEXT_CHANGED,
          payload: {
            text: 'some new text',
            noteId: 42
          }
        });
      });
    });
  });

}).call(this);
